[shell]
program = "/usr/bin/fish"

[font]
size = 10.7
normal = { family = "GeistMono Nerd Font", style = "SemiBold" }
bold   = { family = "GeistMono Nerd Font", style = "Black" }
# normal = { family = "IosevkaTerm Nerd Font", style = "Bold" }
# normal = { family = "JuliaMono", style = "Bold" }
# normal = { family = "BlexMono Nerd Font", style = "SemiBold" }

builtin_box_drawing = true

[window]
padding = { x = 16, y = 8 }
dynamic_padding = true
# opacity = 0.85

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#f9f9f9'
foreground = '#586e75'

[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'
