[shell]
program = "/usr/bin/fish"

[font]
size = 11.5
normal = { family = "GeistMono Nerd Font", style = "SemiBold" }
bold   = { family = "GeistMono Nerd Font", style = "Black" }
# normal = { family = "IosevkaTerm Nerd Font", style = "Bold" }
# normal = { family = "JuliaMono", style = "Bold" }
# normal = { family = "BlexMono Nerd Font", style = "SemiBold" }

builtin_box_drawing = true

[window]
padding = { x = 16, y = 8 }
dynamic_padding = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#101010'
foreground = '#DCD7BA'

[colors.normal]
black   = '#0d0c0c'
blue    = '#8ba4b0'
cyan    = '#8ea4a2'
green   = '#8a9a7b'
magenta = '#a292a3'
red     = '#c4746e'
white   = '#C8C093'
yellow  = '#c4b28a'

[colors.bright]
black   = '#a6a69c'
blue    = '#7FB4CA'
cyan    = '#7AA89F'
green   = '#87a987'
magenta = '#938AA9'
red     = '#E46876'
white   = '#c5c9c5'
yellow  = '#E6C384'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
