[shell]
program = "/usr/bin/fish"

[font]
size = 10.7
normal = { family = "GeistMono Nerd Font", style = "SemiBold" }
bold   = { family = "GeistMono Nerd Font", style = "Black" }

builtin_box_drawing = true

[window]
padding = { x = 16, y = 8 }
dynamic_padding = true
# opacity = 0.85

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = '#ffffff'
foreground = '#212121'

[colors.cursor]
background = '#212121'
foreground = '#ffffff'

[colors.normal]
black   = '#212121'
red     = '#212121'
green   = '#212121'
yellow  = '#212121'
blue    = '#212121'
magenta = '#212121'
cyan    = '#212121'
white   = '#ffffff'
